"""Select useful OdorNet/Keller candidates for a multi-source OpenSmell demo.

The script:

1. loads the Keller/Vosshall psychophysical dataset;
2. loads enriched OdorNet;
3. loads the previously generated Keller -> PubChem identity cache;
4. joins the datasets by exact PubChem InChIKey;
5. keeps Keller observations where FLOWER, GRASS and WOOD are all available;
6. summarizes those observations without treating OdorNet categories as
   quantitative intensities;
7. ranks molecules that are useful for an OpenSmell multi-source example.

No OpenSmell document is generated by this script.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

KELLER_PATH = PROJECT_ROOT / "examples" / "keller_vosshall.xlsx"
ODORNET_PATH = PROJECT_ROOT / "examples" / "odornet_enriched.csv"
CACHE_PATH = PROJECT_ROOT / "examples" / "keller_pubchem_identity_cache.json"

OUTPUT_CSV = (
    PROJECT_ROOT
    / "examples"
    / "odornet_keller_candidate_ranking.csv"
)


ODORNET_COLUMNS = [
    "floral",
    "green&herbal",
    "woody&mossy",
]

KELLER_COLUMNS = [
    "FLOWER",
    "GRASS",
    "WOOD",
]


def clean(value: Any) -> Any:
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass

    if hasattr(value, "item"):
        try:
            return value.item()
        except (ValueError, AttributeError):
            pass

    return value


def source_key(value: Any) -> str | None:
    """Reproduce the identity keys used by the intersection script."""

    value = clean(value)

    if value is None:
        return None

    text = str(value).strip()

    if not text:
        return None

    if text.isdigit():
        return f"cid:{int(text)}"

    return f"cas:{text}"


def load_cache() -> dict[str, dict[str, Any]]:
    with CACHE_PATH.open(
        "r",
        encoding="utf-8",
    ) as handle:
        cache = json.load(handle)

    if not isinstance(cache, dict):
        raise RuntimeError(
            "PubChem identity cache must contain a JSON object"
        )

    return cache


def load_keller() -> pd.DataFrame:
    frame = pd.read_excel(
        KELLER_PATH,
        sheet_name="data",
        header=2,
    )

    frame.columns = [
        str(column).strip()
        for column in frame.columns
    ]

    return frame


def load_odornet() -> pd.DataFrame:
    return pd.read_csv(
        ODORNET_PATH
    )


def build_odornet_index(
    frame: pd.DataFrame,
) -> dict[str, list[dict[str, Any]]]:

    result: dict[str, list[dict[str, Any]]] = {}

    for index, row in frame.iterrows():

        inchikey = clean(
            row["PubChem_InChIKey"]
        )

        status = clean(
            row["PubChem_Status"]
        )

        if status != "resolved":
            continue

        if not isinstance(inchikey, str):
            continue

        inchikey = inchikey.strip()

        if not inchikey:
            continue

        result.setdefault(
            inchikey,
            [],
        ).append(
            {
                "row": int(index),
                "title": clean(
                    row["PubChem_Title"]
                ),
                "smiles": clean(
                    row["SMILES"]
                ),
                "floral": clean(
                    row["floral"]
                ),
                "green&herbal": clean(
                    row["green&herbal"]
                ),
                "woody&mossy": clean(
                    row["woody&mossy"]
                ),
            }
        )

    return result


def numeric(value: Any) -> float | None:

    value = clean(value)

    if value is None:
        return None

    try:
        number = float(value)
    except (TypeError, ValueError):
        return None

    if not 0.0 <= number <= 100.0:
        return None

    return number


def binary(value: Any) -> int | None:

    value = clean(value)

    if value is None:
        return None

    try:
        number = float(value)
    except (TypeError, ValueError):
        return None

    if number == 0.0:
        return 0

    if number == 1.0:
        return 1

    return None


def main() -> None:

    print("Loading datasets...")

    keller = load_keller()
    odornet = load_odornet()
    cache = load_cache()

    odornet_index = build_odornet_index(
        odornet
    )

    observations: dict[
        tuple[str, int],
        list[dict[str, Any]],
    ] = {}

    identity_metadata: dict[
        tuple[str, int],
        dict[str, Any],
    ] = {}

    for row_index, row in keller.iterrows():

        key = source_key(
            row["CID"]
        )

        if key is None:
            continue

        identity = cache.get(key)

        if not identity:
            continue

        if identity.get("status") != "resolved":
            continue

        inchikey = identity.get(
            "inchikey"
        )

        if not isinstance(inchikey, str):
            continue

        odornet_rows = odornet_index.get(
            inchikey,
            [],
        )

        if not odornet_rows:
            continue

        flower = numeric(
            row["FLOWER"]
        )
        grass = numeric(
            row["GRASS"]
        )
        wood = numeric(
            row["WOOD"]
        )

        if (
            flower is None
            or grass is None
            or wood is None
        ):
            continue

        for odornet_row in odornet_rows:

            group_key = (
                key,
                odornet_row["row"],
            )

            observations.setdefault(
                group_key,
                [],
            ).append(
                {
                    "keller_row": int(row_index),
                    "subject": clean(
                        row[
                            "Subject # (this study)"
                        ]
                    ),
                    "dilution": clean(
                        row["Odor dilution"]
                    ),
                    "flower": flower,
                    "grass": grass,
                    "wood": wood,
                }
            )

            identity_metadata[group_key] = {
                "source_key": key,
                "pubchem_cid": identity.get(
                    "cid"
                ),
                "inchikey": inchikey,
                "keller_name": clean(
                    row["Odor"]
                ),
                "keller_cas": clean(
                    row["C.A.S."]
                ),
                "odornet_row": odornet_row[
                    "row"
                ],
                "odornet_title": odornet_row[
                    "title"
                ],
                "odornet_smiles": odornet_row[
                    "smiles"
                ],
                "odornet_floral": binary(
                    odornet_row["floral"]
                ),
                "odornet_green_herbal": binary(
                    odornet_row[
                        "green&herbal"
                    ]
                ),
                "odornet_woody_mossy": binary(
                    odornet_row[
                        "woody&mossy"
                    ]
                ),
            }

    output_rows: list[dict[str, Any]] = []

    for group_key, rows in observations.items():

        metadata = identity_metadata[
            group_key
        ]

        frame = pd.DataFrame(rows)

        flower_mean = float(
            frame["flower"].mean()
        )
        grass_mean = float(
            frame["grass"].mean()
        )
        wood_mean = float(
            frame["wood"].mean()
        )

        known_categories = [
            value
            for value in [
                metadata[
                    "odornet_floral"
                ],
                metadata[
                    "odornet_green_herbal"
                ],
                metadata[
                    "odornet_woody_mossy"
                ],
            ]
            if value is not None
        ]

        present_count = sum(
            value == 1
            for value in known_categories
        )

        known_count = len(
            known_categories
        )

        keller_signal = (
            flower_mean
            + grass_mean
            + wood_mean
        )

        keller_spread = (
            max(
                flower_mean,
                grass_mean,
                wood_mean,
            )
            - min(
                flower_mean,
                grass_mean,
                wood_mean,
            )
        )

        # Ranking is only for choosing a useful demonstration.
        #
        # It does NOT claim semantic equivalence between:
        # floral <-> FLOWER
        # green&herbal <-> GRASS
        # woody&mossy <-> WOOD
        #
        # Prefer:
        # - complete OdorNet information;
        # - at least one positive OdorNet category;
        # - multiple usable Keller observations;
        # - visible differentiation in Keller measurements.

        score = (
            known_count * 1000
            + present_count * 500
            + min(len(rows), 20) * 20
            + keller_spread
            + keller_signal / 10.0
        )

        best_row = max(
            rows,
            key=lambda item: (
                max(
                    item["flower"],
                    item["grass"],
                    item["wood"],
                )
                - min(
                    item["flower"],
                    item["grass"],
                    item["wood"],
                )
            ),
        )

        output_rows.append(
            {
                **metadata,
                "keller_observation_count": (
                    len(rows)
                ),
                "flower_mean": round(
                    flower_mean,
                    3,
                ),
                "grass_mean": round(
                    grass_mean,
                    3,
                ),
                "wood_mean": round(
                    wood_mean,
                    3,
                ),
                "keller_spread": round(
                    keller_spread,
                    3,
                ),
                "best_keller_row": (
                    best_row["keller_row"]
                ),
                "best_subject": (
                    best_row["subject"]
                ),
                "best_dilution": (
                    best_row["dilution"]
                ),
                "best_flower": (
                    best_row["flower"]
                ),
                "best_grass": (
                    best_row["grass"]
                ),
                "best_wood": (
                    best_row["wood"]
                ),
                "selection_score": round(
                    score,
                    3,
                ),
            }
        )

    output = pd.DataFrame(
        output_rows
    )

    if output.empty:
        raise RuntimeError(
            "No usable multi-source candidates found"
        )

    output = output.sort_values(
        by=[
            "selection_score",
            "keller_spread",
        ],
        ascending=False,
    ).reset_index(
        drop=True
    )

    output.to_csv(
        OUTPUT_CSV,
        index=False,
    )

    print()
    print(
        f"Usable candidates: {len(output):,}"
    )

    print(
        f"Ranking written to: {OUTPUT_CSV}"
    )

    print()
    print("=== TOP 20 ===")
    print()

    columns = [
        "pubchem_cid",
        "keller_name",
        "odornet_floral",
        "odornet_green_herbal",
        "odornet_woody_mossy",
        "keller_observation_count",
        "flower_mean",
        "grass_mean",
        "wood_mean",
        "best_keller_row",
        "best_subject",
        "best_dilution",
        "best_flower",
        "best_grass",
        "best_wood",
        "selection_score",
    ]

    print(
        output[
            columns
        ].head(20).to_string(
            index=False
        )
    )


if __name__ == "__main__":
    main()